name: Build docs

on:
  workflow_call:
    inputs:
      pip-install-deps:
        description: "The option and arg to pip install from"
        type: string
        default: ".[docs]"

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch all history and tags for git-revision-date-localized-plugin
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install required packages
        run: python -m pip install ${{ inputs.pip-install-deps }}
      - name: Setup caching
        uses: actions/cache@v3
        with:
          key: ${{ github.sha }}
          path: .cache
      - name: Build site (_site directory name is used for Jekyll compatiblity)
        run: mkdocs build --strict --config-file ./mkdocs.yml --site-dir ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
